export const colors = {
  //light colors
  background_light: '#F7F3F3',
  background_variant_light: '',
  primary_light: '#C2F9FF',
  secondary_light: '',
  tertiary_light: '',
  error_light: '',
  info_light: '',
  warning_light: '',
  success_light: '#77BB8E',
  light_brown: '#E7DFC6',
  text_light: '#F7F3F3',
  //dark colors
  background_dark: '#06090E',
  background_variant_dark: '#30323D',
  primary_dark: '',
  secondary_dark: '#0F7173',
  tertiary_dark: '#F1DACA',
  error_dark: '#DF3B57',
  info_dark: '',
  warning_dark: '',
  success_dark: '',
  dark_brown: '#816C61',
  text_dark: '#161B33',
};
